# Tagging.destroy_all
# Tag.destroy_all
Comment.destroy_all
Negative.destroy_all
User.destroy_all
Photo.destroy_all



Adrian = Wdier.create!(name: "Adrian Maseda", img_url: "http://orig02.deviantart.net/789b/f/2011/284/c/0/minus_the_bear_logo_by_mrjiggles4-d4cjd90.png", squad_name: "", squad_id: 1, quote: "", teaching: "", memory: "", favlang: "", wisewords: "", email: "amaseda@ga.com", password: "coders")

Becky = Wdier.create!(name: "Becky Beauchamp", img_url: "https://pbs.twimg.com/profile_images/566317879713214465/jzp0Z10y.jpeg", squad_name: "", squad_id: 2, quote: "", teaching: "", memory: "", favlang: "", wisewords: "", email: "bbeauchamp@ga.com", password: "coders")

Jesse = Wdier.create!(name: "Jesse Shawl", img_url: "https://pbs.twimg.com/profile_images/494612822740197377/4ldXwgN5_400x400.jpeg", squad_name: "Jesse and the Rippers", squad_id: 3, quote: "", teaching: "", memory: "", favlang: "", wisewords: "", email: "jshawl@ga.com", password: "coders")

Joe = Wdier.create!(name: "Joe Zaretsky", img_url: "http://media.vogue.com/r//2015/03/11/cinderella-gifs-steven-dam-06.gif", squad_name: "", squad_id: 4, quote: "", teaching: "", memory: "", favlang: "", wisewords: "", email: "jzaretsky@ga.com", password: "coders")

Matt = Wdier.create!(name: "Matt Scilipoti", img_url: "https://avatars0.githubusercontent.com/u/31929?v=3&s=400", squad_name: "", squad_id: 5, quote: "", teaching: "", memory: "", favlang: "", wisewords: "", email: "mscilipoti@ga.com", password: "coders")
Nick = Wdier.create!(name: "Nick Olds", img_url: "http://i.giphy.com/1Lks5PFkIekO4.gif", squad_name: "", squad_id: 6, quote: "", teaching: "", memory: "", favlang: "", wisewords: "", email: "nolds@ga.com", password: "coders")
Robin = Wdier.create!(name: "Robin Thomas", img_url: "https://avatars3.githubusercontent.com/u/6268177?v=3&s=460", squad_name: "Team Water Cooler", squad_id: 7, quote:"They don't think it be like it is, but it do.", teaching: 1.5, memory:"Watching the kickass Project 3 presentations!", favlang:"Javascript", wisewords:"Go teach! Do a free 'Beginner's HTML' class at your library or church. What you have, everyone else wants!", email: "rthomas@ga.com", password: "coders")

Adrian2 = Wdier.create!(name: "Adrian Wyatt", img_url: "http://imgur.com/AFP96hi", github_url:"https://github.com/Wyatt23", portfolio_url:"", project1_url:"", project2_url:"", project3_url:"", quote:"Everything can be undone, except the thing you didn't do.", instructor_id: 1, squad_id: 1, q1: "my naive sense of defiant romanticism..well, that and my GPS.", q2: "", q3: "", fb: "https://www.facebook.com/AdrianWyatt23", linkedin: "https://www.linkedin.com/in/adrianwyatt", email: "AdrianWyatt@gmail.com ", password: "coders")

Alexa = Wdier.create!(name: "Alexa Klein", img_url:"https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAYHAAAAJGE2OWQ0ZDk2LTE1MTctNDc4Mi05ZWUzLTE5ZTExOTUwZTM4OA.jpg", github_url: "www.github.com/aklein916", portfolio_url: "http://aklein916.github.io/", project1_url: "http://aklein916.github.io/project1/", project2_url: "https://alexas-dc-workout-guide.herokuapp.com/", project3_url: "https://icare-volunteer-app.herokuapp.com/", quote: "If you don't know where you are going, any road will get you there --Alice and Wonderland", instructor_id: 1, squad_id: 1, q1: "I have loved meeting and learning from such a diverse and awesome group of people.", q2: "Iced Coffee", q3: "binge-watching a TV series", fb: "facebook.com/alexamklein", linkedin: "www.linkedin.com/in/alexaklein", email: "lexi.klein1@gmail.com", password: "coders")

Andrew = Wdier.create!(name: "Andrew Smith-Mui", img_url:"", github_url: "", portfolio_url: "", project1_url:  "", project2_url: "", project3_url: "", quote: "", instructor_id: 1, squad_id: 1, q1: "", q2: "", q3: "", fb: "", linkedin: "", email: "asmith-mui@ga.com", password: "coders")
Anissa = Wdier.create!(name: "Anissa Jones", img_url: "", github_url: "https://github.com/SuperJones", portfolio_url: "", project1_url: "", project2_url: "https://steps-battle.herokuapp.com/", project3_url: "https://vivalavegan.herokuapp.com/", quote: "When you want something, all the universe conspires in helping you to achieve it. --Paulo Coehlo", instructor_id: 1, squad_id: 1, q1: "Wombat", q2: "My phone - though I still forget my one-on-ones", q3: "I'm not guilty about it but anything zombie related even though they give me nightmares." , fb: "", linkedin: "https://www.linkedin.com/in/anissadjones", email: "anissajones10@gmail.com", password: "coders")

Bipin = Wdier.create!(name: "Bipin Neupane", img_url: "https://scontent-lga3-1.xx.fbcdn.net/hphotos-xla1/v/t1.0-9/12347981_10153799731311052_2603207577644789666_n.jpg?oh=10cfd5dc73cb6c3a0520d667bf43ca69&oe=57C0230B", github_url: "https://github.com/Bneupane", portfolio_url: "http://bneupane.github.io", project1_url: "http://bneupane.github.io/memory-game/", project2_url: "http://projectcheerup.herokuapp.com", project3_url: "http://whereismystuff.herokuapp.com", quote: "'Nyron is trying to unfuck me.' -- some UXDI girl", instructor_id: 2, squad_id: 2, q1: "When I performed 'My Relationship with Ruby' poem and the crowd went bananas!", q2: "iPhone, glasses, laptop, friends, happy hour", q3: "Looking at solution branch.", fb: "https://www.facebook.com/NeuBip", linkedin: "", email: "icomp2@hotmail.com", password: "coders")

Brendan = Wdier.create!(name: "Brendan Magee", img_url: "http://i.imgur.com/msYfTL5l.jpg?1", github_url: "https://github.com/brendaneamon", portfolio_url: "http://brendaneamon.github.io/", project1_url: "http://brendaneamon.github.io/project1-flashcards/", project2_url: "https://kleos-app.herokuapp.com/", project3_url: "http://zoosnapz.herokuapp.com/", quote: "forsan et haec olim meminisse iuvabit. (Maybe someday you'll rejoice to remember even this.) —P. Vergilius Maro (The Aeneid, Book I, line 203)", instructor_id: 1, squad_id: 1, q1: "Bipin's GA happy hour poetry slam performance", q2: "The complete oeuvre of the band Rush", q3: "Cookie Clicker, obvi", fb: "https://www.facebook.com/Brendan.Eamon", linkedin: "https://www.linkedin.com/in/brendaneamonmagee", email: "bmagee@gmail.com", password: "coders")

Brittany = Wdier.create!(name: "Brittany Branson", img_url: "", github_url: "", portfolio_url: "", project1_url: "", project2_url: "", project3_url: "", quote: "", instructor_id: 2 , squad_id: 2, q1: "", q2: "", q3: "", fb: "", linkedin: "", email: "bbranson@ga.com", password: "coders")

Caitlin = Wdier.create!(name: "Caitlin Daitch", img_url:  "https://scontent-lga3-1.xx.fbcdn.net/hphotos-xlp1/v/t1.0-9/12718087_1194207560621759_5398938579378409241_n.jpg?oh=593f5a4f31ef57d8a8ff5a8c3f8dfeca&oe=57BE42ED",github_url:  "https://github.com/caitlindaitch", portfolio_url: "www.caitlindaitch.com", project1_url: "http://caitlindaitch.github.io/ConcentrationGame/", project2_url: "https://bar-in-mind.herokuapp.com/", project3_url: "", quote: "", instructor_id: 2, squad_id: 2, q1: "", q2: "", q3: "", fb: "https://www.facebook.com/caitlin.dejcz", linkedin: "https://www.linkedin.com/in/caitlindaitch", email: "caitlin.daitch@gmail.com", password: "coders")

Cam = Wdier.create!(name: "Cam Latimer", img_url: "", github_url: "", portfolio_url: "", project1_url: "", project2_url: "", project3_url: "", quote:"" , instructor_id: 2, squad_id: 2, q1: "", q2: "", q3: "", fb: "", linkedin: "", email: "clatimer@ga.com", password: "coders")

Casey = Wdier.create!(name: "Casey Gil", img_url: "", github_url: "", portfolio_url: "", project1_url: "", project2_url: "", project3_url: "", quote: "", instructor_id: 2, squad_id: 2, q1: "", q2: "", q3: "", fb: "", linkedin: "", email: "cgil@ga.com", password: "coders")

Charles = Wdier.create!(name: "Charles Hwang", img_url:  "http://i.imgur.com/htWHGUV.jpg", github_url:  "https://github.com/charlesthwang", portfolio_url: "charlesthwang.github.io", project1_url: "", project2_url: "https://climbr-beta.herokuapp.com/", project3_url: "http://zoosnapz.herokuapp.com", quote: "With hard work and determination, you can even!", instructor_id: 2, squad_id: 2, q1: "Open Mic Night", q2: "Glasses/Contacts", q3: "Late-night talk shows", fb: "http://facebook.com/charlesthwang", linkedin: "https://www.linkedin.com/in/charlesthwang", email: "charlesthwang@gmail.com", password: "coders")

Christine = Wdier.create!(name: "Christine Movius", img_url: "http://i.imgur.com/qJ7gZy2l.jpg", github_url: "https://github.com/cmmovius", portfolio_url: "http://www.christinemovius.com/",  project1_url: "https://dndr.herokuapp.com/", project2_url: "http://zoosnapz.herokuapp.com/", project3_url: "", quote: "'Only those who risk going too far can possibly find out how far one can go.' -T.S. Eliot", instructor_id: 2, squad_id: 2, q1: "The moments when I witness a fellow classmate celebrating after finally getting their code to work after struggling through a really hard problem.", q2: "Chapstick. I can't go anywhere without it!", q3: "Watching streams of the video game, Hearthstone. But I'm not guilty about it!", fb: "https://www.facebook.com/christine.marian13", linkedin: "https://www.linkedin.com/in/christinemovius", email: "christine.movius@gmail.com", password: "coders")

Clarissa = Wdier.create!(name:"Clarissa Stark", img_url: "", github_url: "", portfolio_url: "", project1_url: "", project2_url: "", project3_url: "", quote: "", instructor_id: 3, squad_id: 3, q1: "", q2: "", q3: "", fb: "", linkedin: "", email: "cstark@ga.com", password: "coders")

Craig = Wdier.create!(name:"Craig Eisen", img_url: "http://i.imgur.com/00vZ2AHl.jpg?1", github_url: "https://github.com/Ceisen9", portfolio_url: "", project1_url: "", project2_url: "https://craig-eisen-bestbet-rails.herokuapp.com/", project3_url: "http://johnblakeman.com:7777/#/", quote: "A wizard is never late, nor is he early, he arrives precisely when he means to. -Lord of the Rings: The Return of the King", instructor_id: 3, squad_id: 3, q1: "I do not have a specific memory, but will always remember the enthusiasm shared by the teachers, students, and admins at GA", q2: "Good food and coffee", q3: "Binge watching online tv in lieu of sleeping", fb: "https://www.facebook.com/craig.eisen", linkedin: "https://www.linkedin.com/in/craigeisen", email: "ceisen91@gmail.com", password: "coders")
Farishta = Wdier.create!(name:"Farishta Haider", img_url: "", github_url: "", portfolio_url: "", project1_url: "", project2_url: "", project3_url: "https://icare-volunteer-app.herokuapp.com/", quote: "", instructor_id: 3, squad_id: 3, q1: "", q2: "", q3: "", fb: "", linkedin: "", email: "farishta.haider@gmail.com", password: "superman")
Hilary = Wdier.create!(name:"Hilary Masland", img_url: "http://i.imgur.com/AkpYyvHl.jpg", github_url: "https://github.com/hilarymasland", portfolio_url: "", project1_url: "", project2_url: "", project3_url: "", quote: "'Everything you can imagine is real' - Picasso", instructor_id: 3, squad_id: 3, q1: "When Mohammed defined 'sharding' ---still laughing.", q2: "", q3: "pretzels, goldfish, family guy, bloody mary's", fb: "https://www.facebook.com/grizzly.masland", linkedin: "https://www.linkedin.com/in/maslandhilary", email: "hilarymasland@gmail.com", password: "coders")
Isaac = Wdier.create!(name:"Isaac Hayes", img_url: "", github_url: "https://github.com/crunchwrap78 ", portfolio_url: "", project1_url: "", project2_url: "", project3_url: "" , quote: "'It is better to be pissed off than be pissed on' or 'life may not be the party we'd hope for, but while we're here, we might as well dance'", instructor_id: 3, squad_id: 3, q1: "Learning how to make rails apps", q2: "Glasses", q3: "", fb: "", linkedin: "", email: "ihayes@ga.com", password: "coders")

Fatai = Wdier.create!(name:"Fatai Agiri", img_url: "", github_url: "", portfolio_url: "", project1_url: "", project2_url: "", project3_url: "" ,quote: "", instructor_id: 1, squad_id: 1, q1: "", q2: "", q3: "", fb: "", linkedin: "", email: "fagiri@ga.com", password: "coders")

Jeffrey = Wdier.create!(name:"Jeffrey Eaton", img_url: "https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAaoAAAAJGRjNjIwMmViLTExYWQtNDViOC1iNjg2LTQ4NzBhYTBlNTZmNg.jpg", github_url: "https://github.com/jeffreyeaton76", portfolio_url: "http://jeffreyeaton76.github.io/", project1_url: "https://jeffreyeaton76-lifelist.herokuapp.com/", project2_url: "https://jeffreyeaton76-ihavetogo.herokuapp.com/", project3_url: "http://cryptly.herokuapp.com/", quote: "", instructor_id: 4, squad_id: 4, q1: "", q2: "coffee", q3: "", fb: "https://www.facebook.com/profile.php?id=100010912957903", linkedin: "https://www.linkedin.com/in/jeffreyeaton76", email: "jeffreyeaton.dc@gmail.com", password: "coders")

John = Wdier.create!(name:"John Blakeman", img_url: "http://i.imgur.com/8YBxfQEl.jpg", github_url: "https://www.github.com/jblakeman", portfolio_url: "", project1_url: "", project2_url: "", project3_url: "" ,quote: "", instructor_id: 4, squad_id: 4, q1: "", q2: "", q3: "", fb: "", linkedin: "", email: "jblakeman@ga.com", password: "coders")

Kiara = Wdier.create!(name:"Kaira Johnson", img_url: "http://i.imgur.com/21ivHG5l.jpg", github_url: "https://github.com/kairajohnson", portfolio_url: "IAMNichol.com", project1_url: "https://github.com/kairajohnson/project1", project2_url: "", project3_url: "", quote: "", instructor_id: 4, squad_id: 4, q1: "", q2: "", q3: "", fb: "", linkedin: "", email: "kjohnson@ga.com", password: "coders")

Keith = Wdier.create!(name:"Keith Prifte", img_url: "http://i.imgur.com/VIpdgf2l.jpg", github_url: "", portfolio_url: "", project1_url: "", project2_url: "", project3_url: "" ,quote: "", instructor_id: 4, squad_id: 4, q1: "", q2: "", q3: "", fb: "https://www.facebook.com/keith.prifte", linkedin: "https://www.linkedin.com/in/keithprifte", email: "kprift@gmail.com", password: "coders")

Kimberly = Wdier.create!(name:"Kimberly Cabbagestock", img_url: "http://i.imgur.com/AE5bcM4.jpg?4", github_url: "github.com/kcabbagestalk", portfolio_url: "kcabbagestalk.github.io", project1_url: "", project2_url: "", project3_url: "", quote: "", instructor_id: 5, squad_id: 5, q1: "", q2: "", q3: "", fb: "", linkedin: "https://www.linkedin.com/in/kimberlycabbagestalk", email: "kim@cabbagestalk.com", password: "coders")

Lyndsey = Wdier.create!(name:"Lyndsey Newsome", img_url: "", github_url: "", portfolio_url: "", project1_url: "", project2_url: "", project3_url: "" ,quote: "Chocolate doesn't ask questions. Chocolate understands...", instructor_id: 5, squad_id:5 , q1: "Almost every project week, homework assignment, and lab.", q2: "Food.", q3: "Nothing. I have no guilt.", fb: "", linkedin: "", email: "lnewsome@ga.com", password: "coders")

MattS = Wdier.create!(name:"Matt Stevens", img_url: "", github_url: "", portfolio_url: "", project1_url: "", project2_url: "", project3_url: "", quote: "", instructor_id: 5, squad_id: 5, q1: "", q2: "", q3: "", fb: "", linkedin: "", email: "mstevens@ga.com", password: "coders")

Matthew = Wdier.create!(name:"Matthew Kerns", img_url: "http://i.imgur.com/qkDjYpQl.jpg", github_url: "https://github.com/mkernsNCR", portfolio_url: "", project1_url: "http://mkernsncr.github.io/project-war", project2_url: "https://pianogram.herokuapp.com/", project3_url: "https://starfax.herokuapp.com/#/" , quote: "", instructor_id: 5, squad_id: 5, q1: "Project Week 2.", q2: "GA Experience.", q3: "Anime", fb: "https://www.facebook.com/mkerns3", linkedin: "https://www.linkedin.com/in/matthewkerns1", email: "matthewkerns@gmail.com", password: "coders")

Maureen = Wdier.create!(name:"Maureen Vogel", img_url: "", github_url: "", portfolio_url: "", project1_url: "", project2_url: "", project3_url: "" ,quote: "", instructor_id: 5, squad_id: 5, q1: "", q2: "", q3: "", fb: "", linkedin: "", email: "mvogel@ga.com", password: "coders")

Maximillian = Wdier.create!(name:"Maximillian Kaye", img_url: "", github_url: "", portfolio_url: "", project1_url: "", project2_url: "", project3_url: "", quote: "", instructor_id: 5, squad_id: 5, q1: "", q2: "", q3: "", fb: "", linkedin: "", email: "mkaye@ga.com", password: "coders")

Melissa = Wdier.create!(name:"Melissa Miller", img_url: "http://i.imgur.com/6oVAGX8l.jpg", github_url: "https://github.com/holytoastr", portfolio_url: "http://holytoastr.github.io/", project1_url: "http://holytoastr.github.io/project1/", project2_url: "https://emotional-corgum.herokuapp.com/", project3_url: "https://jeffreyeaton76-ihavetogo.herokuapp.com/", quote: "'It's kind of fun to do the impossible' --Walt Disney", instructor_id: 6, squad_id: 6, q1: "", q2: "Cell phone's GPS", q3: "Disney World!", fb: "", linkedin: "", email: "lis.d.miller@gmail.com", password: "coders")

Mohamed = Wdier.create!(name:"Mohamed Chalal", img_url: "http://i.imgur.com/GLkF9oDl.png", github_url: "", portfolio_url: "", project1_url: "", project2_url: "", project3_url: "", quote: "", instructor_id: 6, squad_id: 6, q1: "", q2: "", q3: "", fb: "", linkedin: "", email: "mchalal@ga.com", password: "coders")

Nyron = Wdier.create!(name:"Nyron Waite", img_url: "http://i.imgur.com/idU8KFal.jpg", github_url: "https://github.com/nyron", portfolio_url: "https://profiles.generalassemb.ly/profiles/nyron-waite", project1_url: "https://github.com/nyron/TriviaGame.git", project2_url: "http://nyron.github.io/QuickSearch/quicksearch.html ", project3_url: "" ,quote: "No one can make you feel inferior without your consent", instructor_id: 6, squad_id: 6, q1: "Happy Hours!", q2: "Brain", q3: "Chiptole", fb: "", linkedin: "https://www.linkedin.com/in/nyronwaite", email: "nyroncurtiswaite@gmail.com", password: "coders")

Patrick = Wdier.create!(name:"Patrick Moran", img_url: "", github_url: "", portfolio_url: "", project1_url: "", project2_url: "", project3_url: "" ,quote: "", instructor_id: 6, squad_id: 6, q1: "", q2: "", q3: "", fb: "", linkedin: "", email: "pmoran@ga.com", password: "coders")

Robel = Wdier.create!(name:"Robel Tekeste", img_url: "https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAhyAAAAJGZhYjkxOTZkLTA2NGEtNGQ0Ny1hODhhLWE2Zjk0ZWY3OGU2MQ.jpg", github_url: "https://github.com/Robizzy27", portfolio_url: "https://profiles.generalassemb.ly/profiles/robel", project1_url: "", project2_url: "robs-westeros.herokuapp.com", project3_url: "dcvsmarvel.herokuapp.com", quote: "Time is limited, don't waste it living someone else's life. (Steve Jobs)", instructor_id: 6, squad_id: 6, q1: "Juan 'The Wombat' Jaunnsen", q2: "Mac... iPhone... iPad... ", q3: "Binge watching Scrubs, Big Bang Theory, Star Trek Voyager, etc. ", fb: "https://www.facebook.com/Robizzy27", linkedin: "https://www.linkedin.com/in/robeltekeste", email: "Robel.Tekeste@gmail.com", password: "coders")

Ryan = Wdier.create!(name:"Ryan Krolick", img_url: "", github_url: "", portfolio_url: "", project1_url: "", project2_url: "", project3_url: "" ,quote: "", instructor_id: 6, squad_id: 6, q1: "", q2: "", q3: "", fb: "", linkedin: "", email: "rkrolick@ga.com", password: "coders")
Sanjaya = Wdier.create!(name:"Sanjaya Satyal", img_url: "http://i.imgur.com/wNO3nWTm.jpg", github_url: "github.com/ssatyal", portfolio_url: "ssatyal.github.io", project1_url: "ssatyal.github.io/Project-1-War", project2_url: "https://ice-and-fire.herokuapp.com/", project3_url: "https://auto-pilot.herokuapp.com/", quote: "It really tied the room together.", instructor_id: 7, squad_id: 7, q1: "Caitlin wiping out in front of Seth", q2: "text editor", q3: "Wasting time on reddit", fb: "", linkedin: "linkedin.com/in/ssatyal", email: "satyal89@gmail.com", password: "coders")

Sarah = Wdier.create!(name:"Sarah Ivey", img_url: "", github_url: "", portfolio_url: "", project1_url: "", project2_url: "", project3_url: "" ,quote: "", instructor_id: 7, squad_id: 7, q1: "", q2: "", q3: "", fb: "", linkedin: "", email: "sivey@ga.com", password: "coders")

Toni = Wdier.create!(name:"Toni Langley", img_url: "http://i.imgur.com/Dj3nWQ5l.jpg", github_url: "https://github.com/Chibiania", portfolio_url: "https://chibiania.github.io/", project1_url: "http://chibiania.github.io/game-lab/", project2_url: "http://book2adapt.herokuapp.com/", project3_url: "https://the-snack-app.herokuapp.com/#/" ,quote: "Live the Life You Love", instructor_id: 7, squad_id: 7, q1: "Picture Day!", q2: "Cellphone", q3: "Fan fiction (still)", fb: "https://www.facebook.com/langley5", linkedin: "https://www.linkedin.com/in/tlangley", email: "chibia2@gmail.com", password: "coders")

Vi = Wdier.create!(name:"Vijender Bajwa", img_url: "http://imgur.com/CdMFOPE", github_url: "https://github.com/vbajwa", portfolio_url: "", project1_url: "", project2_url: "", project3_url: "", quote: "If it doesn't make you money or it doesn't make you happy its not worth doing. Adam Carolla", instructor_id: 7, squad_id: 7, q1: "That one time we went to the pub. ", q2: "I've never been lost. ", q3: "I have never felt guilty about my hedonism", fb: "", linkedin: "", email: "vjbajwa42@gmail.com", password: "coders")

Winisha = Wdier.create!(name:"Winisha Smith", img_url: "http://i.imgur.com/cu0BhDD.png", github_url: "https://github.com/WinishaSmith", portfolio_url: "", project1_url: "http://winishasmith.github.io/Jeopardy_Winnie/", project2_url: "undone.herokuapp.com", project3_url: "vivalavegan.herokuapp.com", quote: "“No matter how you feel, get up, dress up and show up.” - Regina Brett", instructor_id: 7, squad_id: 7, q1: "Project Showcases & Campus Lunches", q2: "Macbook", q3: "Rom-Coms (Romantic Comedies)", fb: "", linkedin: "https://www.linkedin.com/in/winishasmith", email: "winishasmith@gmail.com", password: "coders")

Woo = Wdier.create!(name:"Woo Yun", img_url: "http://namooyoga.com/wp-content/uploads/2015/09/woosub-1.jpg", github_url: "https://github.com/hh747hh", portfolio_url: "woosubyun.com", project1_url: "https://github.com/hh747hh/project_memory_card", project2_url: "https://github.com/hh747hh/essential-oil-remedies", project3_url: "https://github.com/hh747hh/Project3", quote: "The best way to predict the future is to create it.", instructor_id: 7, squad_id: 7, q1: "Working with fun, smart people.", q2: "Eye glasses", q3: "I love eating ramen at night.", fb: "https://www.facebook.com/woosub.yun.7", linkedin: "https://www.linkedin.com/in/woosubyun", email: "hh747hh@gmail.com", password: "coders")

first_photo = Photo.create!(img_url:"http://cache-blog.credit.com/wp-content/uploads/2013/04/student-loans-ts-1360x860.jpg")
Photo.create!(img_url:"https://www.sdcity.edu/Portals/0/CollegeServices/UserSupportResources/Counseling/new_students.jpg")

second_photo= Photo.create!(img_url:"https://media4.popsugar-assets.com/files/2013/08/12/833/n/1922398/3a9296910b700fb0_tumblr_mj1k17kIL61qfjyrro1_500.xxxlarge.gif")



Jesse.photos << first_photo
Robin.photos << second_photo



gallery1 = Photo.create!(
img_url: "https://lh3.googleusercontent.com/JZ-7KKH5eQVjlODoyt7zOSl3fXCEDx_8PTTs-zxTbqAoxbA9fd7DtQewhsPJGQ3TC2XUKwBRo78m=w2334-h944");

gallery2 = Photo.create!(img_url: "https://lh6.googleusercontent.com/igxyyxt36-04ZLmF3Mupaq2GPdALwLlEYU2x2ToOSxGRfcTGcPcJuZ6NB44UZMzSnCqrNw=w2356-h944");
